import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class FlagService {
  constructor() {}

  getFlagName(nationality: number): string {
    let countryCode: string | undefined;
    switch (nationality) {
      case 1:
        return 'us';
      case 2:
        return 'ra';
      case 3:
        return 'au';
      case 4:
        return 'at';
      case 5:
        return 'az';
      case 6:
        return 'bh';
      case 7:
        return 'be';
      case 8:
        return 'bo';
      case 9:
        return 'br';
      case 10:
        return 'gb';
      case 11:
        return 'bg';
      case 12:
        return 'cm';
      case 13:
        return 'ca';
      case 14:
        return 'cl';
      case 15:
        return 'cn';
      case 16:
        return 'co';
      case 17:
        return 'cr';
      case 18:
        return 'hr';
      case 19:
        return 'cy';
      case 20:
        return 'cz';
      case 21:
        return 'dk';
      case 22:
        return 'nd';
      case 23:
        return 'ec';
      case 24:
        return 'gb';
      case 25:
        return 'ae';
      case 26:
        return 'ee';
      case 27:
        return 'fi';
      case 28:
        return 'fr';
      case 29:
        return 'de';
      case 30:
        return 'gh';
      case 31:
        return 'gr';
      case 32:
        return 'gt';
      case 33:
        return 'hn';
      case 34:
        return 'hk';
      case 35:
        return 'hu';
      case 36:
        return 'is';
      case 37:
        return 'in';
      case 38:
        return 'id';
      case 39:
        return 'ie';
      case 40:
        return 'il';
      case 41:
        return 'it';
      case 42:
        return 'jm';
      case 43:
        return 'jp';
      case 44:
        return 'jo';
      case 45:
        return 'kw';
      case 46:
        return 'lv';
      case 47:
        return 'rl';
      case 48:
        return 'lt';
      case 49:
        return 'lu';
      case 50:
        return 'my';
      case 51:
        return 'mt';
      case 52:
        return 'mx';
      case 53:
        return 'mc';
      case 54:
        return 'nz';
      case 55:
        return 'ni';
      case 56:
        return 'kp';
      case 57:
        return 'gb';
      case 58:
        return 'no';
      case 59:
        return 'om';
      case 60:
        return 'pk';
      case 61:
        return 'pz';
      case 62:
        return 'py';
      case 63:
        return 'pe';
      case 64:
        return 'pl';
      case 65:
        return 'pt';
      case 66:
        return 'qa';
      case 67:
        return 'ro';
      case 68:
        return 'ru';
      case 69:
        return 'sv';
      case 70:
        return 'sa';
      case 71:
        return 'gb';
      case 72:
        return 'rs';
      case 73:
        return 'sg';
      case 74:
        return 'sk';
      case 75:
        return 'si';
      case 76:
        return 'kr';
      case 77:
        return 'za';
      case 78:
        return 'es';
      case 79:
        return 'se';
      case 80:
        return 'ch';
      case 81:
        return 'th';
      case 82:
        return 'tr';
      case 83:
        return 'uy';
      case 84:
        return 'ua';
      case 85:
        return 've';
      case 86:
        return 'gb';
      default:
        throw new Error('could not get country');
    }
  }
}
