name: CI
on:
  push:
    branches: [ master ]

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
    - name: change to angular directory
      run: cd f1-client
    - name: build dockerfile
      run: docker build --tag 13markdocker/f1-client:latest .
