name: CI
on:
  push:
    branches: [ master ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    env:
      working-directory: ./f1-client

    steps:
    - name: build dockerfile
      run: docker build --tag 13markdocker/f1-client:latest .
